name: Self-Hosted Cl

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  security:
    runs-on: self-hosted #se ejecuta el runner self -hosted
    steps:
      - name: Checkou del codigo
        uses: actions/checkout@v4
        
      - name: Ejecutar analisis estatico con Snyk Code
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      
