name: Self-Hosted Cl

on:
  push:
    branches:
      -master
jobs:
  security:
    runs-on: self-hosted #se ejecuta el runner self -hosted
    steps:
      - name: Checkou del codigo
        uses: actions/checkout@v4

      
